interface GuardrailBannerProps {
  /** The exact banner text enforced server-side (see agent.report.INTERPRETATION_BANNER). */
  text: string;
  /**
   * Server-side guardrail violations (`guardrail_violations` in the API
   * response). Empty/omitted means the assessment is fully compliant.
   */
  violations?: string[];
}

/**
 * Mandatory, unmissable guardrail banner.
 *
 * Every AI-drafted variant assessment produced by this platform must carry
 * this banner and cannot be quietly dismissed (see ADR-0008, ADR-0014, and
 * CLAUDE.md's guardrail rule). This component is not closable and is
 * rendered above the fold, before the classification or rationale — a
 * clinician must see it before anything else on the result. The text comes
 * from the API response, not a hardcoded copy, so the UI can never drift
 * from what the server actually enforces.
 */
export function GuardrailBanner({ text, violations = [] }: GuardrailBannerProps) {
  return (
    <div className="guardrail-banner" role="alert" aria-live="assertive">
      <span className="guardrail-banner__icon" aria-hidden="true">
        ⚠
      </span>
      <div className="guardrail-banner__text">
        <strong>{text}</strong>
        <span>
          This assessment was generated by an automated agent. It is not a clinical diagnosis
          and must not be used for patient care until a qualified clinician has reviewed the
          agent trace below and signed off.
        </span>
        {violations.length > 0 && (
          <div className="guardrail-banner__violations">
            <strong>
              {violations.length} guardrail{violations.length === 1 ? '' : 's'} did not pass —
              read before signing off:
            </strong>
            <ul>
              {violations.map((v) => (
                <li key={v}>{v}</li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}
